In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
home_dir = os.getcwd()
data_folder = '//all_data//'
entities = 'Entities.csv'

In [3]:
dir = home_dir + data_folder + entities
print(dir)
df = pd.read_csv(dir, dtype = str)

C:\Users\User\Documents\KE_Project_Work\EB5202-Web Analytics\Graph Analysis//all_data//Entities.csv

In [4]:
df.shape

(495038, 21)

# This is on the Entities as stated in the Panama Papers.

In [5]:
df.head()

,name,original_name,former_name,jurisdiction,jurisdiction_description,company_type,address,internal_id,incorporation_date,inactivation_date,...,dorm_date,status,service_provider,ibcRUC,country_codes,countries,note,valid_until,node_id,sourceID
0,"TIANSHENG INDUSTRY AND TRADING CO., LTD.","TIANSHENG INDUSTRY AND TRADING CO., LTD.",NaN,SAM,Samoa,NaN,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...,1001256,23-MAR-2006,18-FEB-2013,...,NaN,Defaulted,Mossack Fonseca,25221,HKG,Hong Kong,NaN,The Panama Papers data is current through 2015,10000001,Panama Papers
1,"NINGBO SUNRISE ENTERPRISES UNITED CO., LTD.","NINGBO SUNRISE ENTERPRISES UNITED CO., LTD.",NaN,SAM,Samoa,NaN,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...,1001263,27-MAR-2006,27-FEB-2014,...,NaN,Defaulted,Mossack Fonseca,25249,HKG,Hong Kong,NaN,The Panama Papers data is current through 2015,10000002,Panama Papers
2,"HOTFOCUS CO., LTD.","HOTFOCUS CO., LTD.",NaN,SAM,Samoa,NaN,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...,1000896,10-JAN-2006,15-FEB-2012,...,NaN,Defaulted,Mossack Fonseca,24138,HKG,Hong Kong,NaN,The Panama Papers data is current through 2015,10000003,Panama Papers
3,"SKY-BLUE GIFTS & TOYS CO., LTD.","SKY-BLUE GIFTS & TOYS CO., LTD.",NaN,SAM,Samoa,NaN,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...,1000914,06-JAN-2006,16-FEB-2009,...,NaN,Defaulted,Mossack Fonseca,24012,HKG,Hong Kong,NaN,The Panama Papers data is current through 2015,10000004,Panama Papers
4,FORTUNEMAKER INVESTMENTS CORPORATION,FORTUNEMAKER INVESTMENTS CORPORATION,NaN,SAM,Samoa,NaN,LOYAL PORT LIMITED 8/F; CRAWFORD TOWER 99 JERV...,1001266,19-APR-2006,15-MAY-2009,...,NaN,Changed agent,Mossack Fonseca,R25638,HKG,Hong Kong,NaN,The Panama Papers data is current through 2015,10000005,Panama Papers

# Deciding which columns to choose

To do an inital exploration, I have only chosen the Jurisdiction_description as well as country.
Jurisdiction_description means 'the official power to make legal decisions and judgements.'
With this, I assume that the company lies in the particular country
"Country" means where the country operates.

In [6]:
df_edges = df[['name','jurisdiction_description', 'countries', 'incorporation_date','inactivation_date', 'address']]

# Check for Duplicate Records

In [7]:
df_2 = df_edges[df_edges.duplicated(subset = ['name','jurisdiction_description', 'countries', 'incorporation_date','inactivation_date', 'address'], 
                        keep = False)]

In [8]:
df_edges = df_edges.drop_duplicates(subset = ['name','jurisdiction_description', 'countries', 'incorporation_date','inactivation_date', 'address']
                        ,keep = 'first')

In [9]:
df_edges

,name,jurisdiction_description,countries,incorporation_date,inactivation_date,address
0,"TIANSHENG INDUSTRY AND TRADING CO., LTD.",Samoa,Hong Kong,23-MAR-2006,18-FEB-2013,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
1,"NINGBO SUNRISE ENTERPRISES UNITED CO., LTD.",Samoa,Hong Kong,27-MAR-2006,27-FEB-2014,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
2,"HOTFOCUS CO., LTD.",Samoa,Hong Kong,10-JAN-2006,15-FEB-2012,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
3,"SKY-BLUE GIFTS & TOYS CO., LTD.",Samoa,Hong Kong,06-JAN-2006,16-FEB-2009,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
4,FORTUNEMAKER INVESTMENTS CORPORATION,Samoa,Hong Kong,19-APR-2006,15-MAY-2009,LOYAL PORT LIMITED 8/F; CRAWFORD TOWER 99 JERV...
5,8808 HOLDING LIMITED,Samoa,Hong Kong,05-JAN-2006,NaN,TWC MANAGEMENT LIMITED SUITE D; 19/F RITZ PLAZ...
6,KENT DEVELOPMENT LIMITED,Samoa,Hong Kong,26-JAN-2004,03-MAY-2006,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
7,BONUS TRADE LIMITED,Samoa,Hong Kong,13-FEB-2004,16-FEB-2009,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
8,AMARANDAN LTD.,Samoa,Hong Kong,26-JAN-2004,03-MAY-2006,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
9,NEW IDEA LIMITED,Samoa,Hong Kong,30-MAR-2004,27-FEB-2007,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
10,HUGH POWER LIMITED,Samoa,Hong Kong,30-MAR-2004,02-JAN-2008,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
11,ULTIMATE GROUP LIMITED,Samoa,Hong Kong,05-APR-2004,NaN,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
12,VICTORY GROUP LIMITED,Samoa,Taiwan,30-MAR-2004,20-FEB-2010,GO SHINE MANAGEMENT CO.; LTD. ROOM B; 5F.; NO....
13,CHARTER MARK LIMITED,Samoa,China,13-FEB-2004,17-FEB-2011,"AFOR LAW FIRM, SICHUAN CHENGDU SHUANGNAN PIK W..."
14,"Wide International Trading Co., Ltd.",Samoa,Hong Kong,06-JAN-2006,NaN,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
15,HTSS ET CAPITAL LIMITED,Samoa,Hong Kong,21-AUG-2006,19-FEB-2015,TWC MANAGEMENT LIMITED SUITE D; 19/F RITZ PLAZ...
16,JIE LUN INVESTMENT LIMITED,Samoa,Hong Kong,10-APR-2006,NaN,MEI SERVICES LIMITED ROOM E; 6TH FLOOR; EASTER...
17,FORTUNE PALACE LIMITED,Samoa,China,29-MAR-2004,03-MAY-2006,"AFOR LAW FIRM, SICHUAN CHENGDU SHUANGNAN PIK W..."
18,LAKE STREET INVESTMENTS LTD.,Samoa,Switzerland,06-FEB-2004,01-FEB-2005,FCI LTD. ATT.: MR. DAVID RISBEY POSTFACH 24 72...
19,"NINGBO RAPID INTERNATIONAL TRADING CO., LTD.",Samoa,Hong Kong,12-JAN-2006,27-FEB-2014,ORION HOUSE SERVICES (HK) LIMITED ROOM 1401; 1...
20,ANGELIKA INTERNATIONAL LTD.,Samoa,Singapore,26-JAN-2004,03-MAY-2006,MOSSACK FONSECA & CO. (SINGAPORE) PTE LTD. 19...
21,CHEM D-T Corp.,Samoa,Taiwan,30-MAR-2004,06-NOV-2009,GO SHINE MANAGEMENT CO.; LTD. ROOM B; 5F.; NO....
22,PRESTIGE INTERNATIONAL CORP.,Samoa,Taiwan,10-JUN-2004,NaN,GO SHINE MANAGEMENT CO.; LTD. ROOM B; 5F.; NO....
23,SUNNY TREASURE INTERNATIONAL LIMITED,Samoa,Taiwan,06-FEB-2004,03-MAY-2006,DI SAN DI MANAGEMENT COMPANY LIMITED 7F- 4; NO...
24,GIT CO INC.,Samoa,Switzerland,21-NOV-2006,30-AUG-2014,MR. SPYRO A. METAXAS RUE DE HESSE 16 CASE POST...
25,EURO INVESTMENT CAPITAL INC.,Samoa,Switzerland,27-OCT-2006,15-FEB-2012,MR. SPYRO A. METAXAS RUE DE HESSE 16 CASE POST...
26,WORLD TOOLS INVESTMENTS CORP.,Samoa,Brazil,19-DEC-2006,29-APR-2009,MIGUEL NETO ADVOGADOS RUA GUARARAPES; 1909 CON...
27,WINESELECTION S.A.,Samoa,Switzerland,29-DEC-2006,19-FEB-2015,"MSG S.A. 5, CH. DE LA VUACHÃˆRE CASE POSTALE 10..."
28,NECY CONSULTANTS LIMITED,Samoa,Hong Kong,22-MAR-2006,NaN,WILLIE MANAGEMENT LIMITED 12TH FLOOR; LUCKY BU...
29,KIND INTERNATIONAL INC.,Samoa,Taiwan,07-SEP-2006,19-FEB-2015,SINO-WEST INTERNATIONAL CO.; LTD. 3F-6; NO. 36...
...,...,...,...,...,...,...
495008,Penlee Foundation,Bahamas,NaN,07-SEP-2015,NaN,NaN
495009,VALHALLA FOUNDATION,Bahamas,NaN,09-SEP-2015,NaN,NaN
495010,Strelka Foundation,Bahamas,NaN,11-SEP-2015,NaN,NaN
495011,The Oasis Family Foundation,Bahamas,NaN,29-SEP-2015,NaN,NaN
495012,HISTORIC CHARLES TOWNE FOUNDATION,Bahamas,NaN,28-SEP-2015,NaN,NaN
495013,IL CARES FOUNDATION,Bahamas,NaN,09-OCT-2015,NaN,NaN
495014,OWN BAHAMAS FOUNDATION,Bahamas,NaN,09-OCT-2015,NaN,NaN
495015,THE MYLES & RUTH MUNROE FOUNDATION,Bahamas,NaN,27-OCT-2015,NaN,NaN
495016,THE FTAR FOUNDATION,Bahamas,NaN,05-NOV-2015,NaN,NaN
495017,Bellemar Community Foundation,Bahamas,NaN,18-NOV-2015,NaN,NaN
495018,THE BIMA FOUNDATION,Bahamas,NaN,25-NOV-2015,NaN,NaN
495019,THE ARISTI FOUNDATION,Bahamas,NaN,24-NOV-2015,NaN,NaN
495020,The Future Private Foundation,Bahamas,NaN,14-DEC-2015,NaN,NaN
495021,The Ertalia Foundation,Bahamas,NaN,08-DEC-2015,NaN,NaN
495022,Earlshill Foundation,Bahamas,NaN,22-DEC-2015,NaN,NaN
495023,GUALCA FOUNDATION,Bahamas,NaN,11-DEC-2015,NaN,NaN
495024,BEACON FOUNDATION,Bahamas,NaN,05-JAN-2016,NaN,NaN
495025,Southern Galaxy Foundation,Bahamas,NaN,05-JAN-2016,NaN,NaN
495026,QUDURAT FOUNDATION,Bahamas,NaN,21-DEC-2015,NaN,NaN
495027,STALLIONS UNITED FOUNDATION,Bahamas,NaN,26-JAN-2016,NaN,NaN
495028,The Paul Mark Hoffenberg Foundation,Bahamas,NaN,21-JAN-2016,NaN,NaN
495029,The GDS Gold Silver Diamond Foundation,Bahamas,NaN,26-JAN-2016,NaN,NaN
495030,CEP Foundation,Bahamas,NaN,18-JAN-2016,NaN,NaN
495031,The Kamla Diamond Foundation,Bahamas,NaN,01-FEB-2016,NaN,NaN
495032,THE KAMALA DIAMOND FOUNDATION,Bahamas,NaN,01-FEB-2016,NaN,NaN
495033,Malno Foundation,Bahamas,NaN,10-FEB-2016,NaN,NaN
495034,HARD WORK LIFE FOUNDATION,Bahamas,NaN,02-FEB-2016,NaN,NaN
495035,FIORDILATTE FOUNDATION,Bahamas,NaN,19-FEB-2016,NaN,NaN
495036,Paweco Foundation,Bahamas,NaN,07-MAR-2016,NaN,NaN
495037,Beli Foundation,Bahamas,NaN,01-MAR-2016,NaN,NaN

In [10]:
df_edges = df_edges[['jurisdiction_description', 'countries']]

In [11]:
df_edges.jurisdiction_description.unique()

array(['Samoa', 'Panama', 'United Kingdom', 'Singapore', 'Nevada',
       'Ras Al Khaimah', 'Isle Of Man', 'British Anguilla', 'Seychelles',
       'Niue', 'Uruguay', 'British Virgin Islands', 'Hong Kong',
       'New Zealand', 'Bahamas', 'Cyprus', 'Malta', 'Belize', 'Jersey',
       'Wyoming', 'Costa Rica', 'Undetermined', 'Cayman',
       'Recorded in leaked files as "fund"', 'Labuan', 'Marshall Islands',
       'Mauritius', 'St. Lucia', 'Malaysia', 'Dubai', 'Vanuatu',
       'Cook Islands', 'Bermuda', 'Brunei', 'Liberia',
       'United States Of America', 'China', 'Thailand', 'Netherlands',
       'Ireland'], dtype=object)

In [12]:
df_edges.countries.unique()

array(['Hong Kong', 'Taiwan', 'China', 'Switzerland', 'Singapore',
       'Brazil', 'Panama', 'Samoa', 'Liechtenstein', 'Spain', 'Thailand',
       'Colombia', 'Jersey', 'Andorra', 'Seychelles', 'Ireland',
       'Belgium', 'Israel', 'Gibraltar', 'Guernsey',
       'United Arab Emirates', 'Cyprus', 'Venezuela', 'Isle of Man',
       'Lebanon', 'Denmark', 'Uruguay', 'Jordan', 'Bahamas',
       'United Kingdom', nan, 'Belize', 'Luxembourg', 'Guatemala',
       'Germany', 'Mauritius', 'Turkey', 'United States', 'Monaco',
       'Estonia', 'Niue', 'Ecuador', 'Czech Republic', 'Netherlands',
       'Hungary', 'Costa Rica', 'Portugal', 'Cayman Islands',
       'South Africa', 'Malta', 'New Zealand', "CÃ´te d'Ivoire",
       'Dominican Republic', 'France', 'Italy', 'Russia', 'Canada',
       'Saudi Arabia', 'Greece', 'Qatar', 'Mexico', 'Peru', 'Bermuda',
       'Australia', 'Saint Kitts and Nevis', 'Argentina', 'El Salvador',
       'Austria', 'American Samoa', 'Paraguay', 'Chile', 'Egypt',
       'Sweden', 'Japan', 'Slovenia', 'Saint Lucia', 'Indonesia',
       'Honduras', 'Saint Vincent and the Grenadines', 'Kuwait', 'Haiti',
       'Zimbabwe', 'Sudan', 'Nicaragua', 'Turks and Caicos Islands',
       'Anguilla', 'Kenya', 'South Korea', 'Romania', 'Norway',
       'British Virgin Islands', 'Philippines', 'Lithuania', 'Viet Nam',
       'Latvia', 'Aruba', 'Bulgaria', 'Ukraine', 'Malaysia', 'Finland',
       'Iran', 'Poland', 'Lesotho', 'Nigeria', 'Mozambique', 'Macao',
       'Georgia', 'Bolivia', 'Yemen', 'CuraÃ§ao', 'India', 'Macedonia',
       'Antigua and Barbuda', 'Morocco', 'Senegal', 'Dominica', 'Namibia',
       'Botswana', 'Liberia', 'Cook Islands', 'Syria',
       'Sint Maarten (Dutch part)', 'Belarus', 'Djibouti', 'Barbados',
       'Tunisia', 'Bahrain', 'Nauru', 'Azerbaijan', 'Pakistan',
       'Uzbekistan', 'Trinidad and Tobago', 'Sri Lanka',
       'U.S. Virgin Islands', 'Cuba', 'Tanzania', 'Puerto Rico', 'Malawi',
       'Chad', 'Guam', 'Oman', 'Croatia', 'Jamaica', 'Mali', 'Montenegro',
       'Kazakhstan', 'Iceland', 'Vanuatu', 'Moldova', 'Angola',
       'Bangladesh', 'Libya', 'Brunei', 'Ghana', 'Cameroon', 'Albania',
       'Zambia', 'Slovakia', 'Not identified;British Virgin Islands',
       'British Virgin Islands;Hong Kong', 'Not identified;Singapore',
       'British Virgin Islands;Singapore',
       'Cyprus;British Virgin Islands', 'Not identified;United States',
       'British Virgin Islands;Cyprus', 'Not identified;United Kingdom',
       'Switzerland;Not identified', 'British Virgin Islands;Russia',
       'United Kingdom;Not identified', 'Not identified',
       'United States;Not identified',
       'British Virgin Islands;Not identified',
       'Not identified;U.S. Virgin Islands',
       'Hong Kong;British Virgin Islands',
       'British Virgin Islands;United Kingdom',
       'Cayman Islands;British Virgin Islands',
       'British Virgin Islands;Cayman Islands',
       'British Virgin Islands;Cook Islands',
       'British Virgin Islands;Guernsey',
       'British Virgin Islands;United States',
       'Malaysia;British Virgin Islands',
       'Singapore;British Virgin Islands', 'Samoa;Cayman Islands',
       'Mauritius;British Virgin Islands', 'Cayman Islands;Samoa',
       'Cayman Islands;Hong Kong',
       'Singapore;Not identified;British Virgin Islands',
       'Samoa;Hong Kong', 'Taiwan;British Virgin Islands',
       'British Virgin Islands;Taiwan', 'Hong Kong;Cayman Islands',
       'British Virgin Islands;Australia',
       'United Kingdom;British Virgin Islands',
       'British Virgin Islands;Brunei',
       'British Virgin Islands;Indonesia',
       'British Virgin Islands;Malaysia',
       'British Virgin Islands;Viet Nam',
       'South Korea;British Virgin Islands',
       'Indonesia;British Virgin Islands', 'China;British Virgin Islands',
       'United States;British Virgin Islands',
       'Netherlands;British Virgin Islands',
       'British Virgin Islands;Singapore;Hong Kong',
       'Hong Kong;Not identified', 'British Virgin Islands;Thailand',
       'British Virgin Islands;South Korea',
       'Cayman Islands;Taiwan;British Virgin Islands',
       'Brunei;British Virgin Islands', 'Hong Kong;Samoa',
       'British Virgin Islands;China',
       'Cayman Islands;British Virgin Islands;Taiwan',
       'Thailand;Hong Kong',
       'Cayman Islands;China;British Virgin Islands',
       'Thailand;British Virgin Islands', 'Singapore;Samoa',
       'Malaysia;Singapore', 'Singapore;Malaysia', 'Marshall Islands',
       'Singapore;Saint Lucia', 'Cayman Islands;Singapore',
       'South Africa;British Virgin Islands',
       'Canada;British Virgin Islands', 'Singapore;Seychelles',
       'Philippines;British Virgin Islands',
       'Hong Kong;Taiwan;British Virgin Islands', 'Mauritius;Singapore',
       'Cook Islands;Singapore', 'Samoa;Singapore',
       'Viet Nam;British Virgin Islands',
       'British Virgin Islands;Hong Kong;Taiwan', 'Hong Kong;Thailand',
       'Singapore;Cayman Islands', 'United Kingdom;Singapore',
       'U.S. Virgin Islands;British Virgin Islands',
       'Singapore;Hong Kong',
       'British Virgin Islands;Singapore;United Kingdom;Hong Kong',
       'Hong Kong;Singapore', 'Samoa;Taiwan', 'Taiwan;Seychelles',
       'Seychelles;Taiwan', 'British Virgin Islands;Indonesia;Singapore',
       'British Virgin Islands;Germany', 'Seychelles;Singapore',
       'Cook Islands;Indonesia', 'United States;Cook Islands',
       'Cook Islands;United States', 'Singapore;Bahamas',
       'Not identified;Cook Islands', 'Cook Islands;Hong Kong',
       'Singapore;Cook Islands', 'Indonesia;Samoa',
       'Mauritius;Not identified', 'Vanuatu;Singapore', 'Singapore;Japan',
       'British Virgin Islands;Philippines', 'Hong Kong;United Kingdom',
       'Fiji;Cook Islands', 'Indonesia;Singapore',
       'Hong Kong;Netherlands', 'Singapore;Mauritius',
       'Not identified;Czech Republic', 'Grenada;Not identified',
       'Switzerland;Singapore', 'British Virgin Islands;Seychelles',
       'Cayman Islands;Cook Islands', 'Cook Islands;Taiwan',
       'Seychelles;Singapore;Malaysia', 'Switzerland;Hong Kong',
       'Malaysia;Not identified', 'Seychelles;Indonesia',
       'Not identified;Malaysia', 'Samoa;Not identified',
       'Not identified;Samoa', 'Not identified;Mauritius', 'Taiwan;Samoa',
       'Panama;Singapore', 'Seychelles;British Virgin Islands',
       'Singapore;Not identified', 'Not identified;Canada',
       'South Korea;Not identified', 'Hong Kong;Malaysia',
       'British Virgin Islands;United Arab Emirates',
       'Russia;Not identified',
       'British Virgin Islands;Antigua and Barbuda',
       'Russia;British Virgin Islands', 'Ukraine;British Virgin Islands',
       'British Virgin Islands;Latvia',
       'United Arab Emirates;Turks and Caicos Islands',
       'British Virgin Islands;Ireland', 'Latvia;British Virgin Islands',
       'United Arab Emirates;British Virgin Islands',
       'Not identified;Latvia', 'Not identified;Hong Kong',
       'Not identified;Ukraine', 'Antigua and Barbuda;Not identified',
       'Cyprus;Not identified', 'British Virgin Islands;Panama',
       'Latvia;Not identified', 'Not identified;Russia',
       'Panama;British Virgin Islands', 'Ireland;British Virgin Islands',
       'Jersey;British Virgin Islands', 'Japan;Cook Islands',
       'Gibraltar;Not identified', 'China;Not identified',
       'Not identified;China', 'Not identified;Panama',
       'British Virgin Islands;Ukraine', 'Samoa;Thailand',
       'Canada;Not identified', 'British Virgin Islands;Canada',
       'Not identified;Switzerland', 'Singapore;India',
       'Malaysia;Hong Kong', 'Not identified;Jersey',
       'Panama;Not identified', 'Czech Republic;British Virgin Islands',
       'Samoa;Cook Islands', 'Not identified;Cyprus',
       'British Virgin Islands;Saint Kitts and Nevis', 'Jersey;Hong Kong',
       'Cook Islands;Cayman Islands', 'Czech Republic;Not identified',
       'Saint Kitts and Nevis;United States', 'Not identified;Ireland',
       'Seychelles;Not identified', 'Ukraine;Not identified',
       'Not identified;Seychelles', 'Israel;Not identified',
       'British Virgin Islands;Jersey', 'Not identified;Gibraltar',
       'Ireland;Not identified', 'Samoa;Malaysia',
       'Austria;British Virgin Islands', 'Malta;Not identified',
       'British Virgin Islands;Czech Republic',
       'British Virgin Islands;Austria',
       'Luxembourg;British Virgin Islands',
       'British Virgin Islands;Luxembourg', 'Panama;Bahamas',
       'Hong Kong;Jersey', 'Not identified;Norway', 'Belize;Hong Kong',
       'CuraÃ§ao;British Virgin Islands', 'Hong Kong;Belize',
       'Not identified;Antigua and Barbuda', 'Malaysia;Cook Islands',
       'Not identified;Israel', 'Cayman Islands;Taiwan',
       'Hong Kong;Cook Islands', 'Belarus;British Virgin Islands',
       'Saint Kitts and Nevis;Not identified', 'Hong Kong;China',
       'Not identified;Netherlands', 'Austria;Not identified',
       'Thailand;Not identified', 'British Virgin Islands;Malta',
       'Jersey;Not identified',
       'Antigua and Barbuda;British Virgin Islands',
       'British Virgin Islands;Sweden', 'Sweden;British Virgin Islands',
       'United States;United Kingdom', 'Gibraltar;British Virgin Islands',
       'Belize;United States', 'Not identified;Bahamas',
       'Not identified;Croatia', 'Not identified;Sweden',
       'Vanuatu;Not identified', 'British Virgin Islands;Vanuatu',
       'United States;Belize', 'Australia;Not identified',
       'Hong Kong;Turks and Caicos Islands',
       'Not identified;Saint Kitts and Nevis',
       'British Virgin Islands;Mauritius', 'Poland;Not identified',
       'Netherlands;Not identified', 'New Zealand;Not identified',
       'Turks and Caicos Islands;Not identified',
       'British Virgin Islands;Gibraltar',
       'Turks and Caicos Islands;Hong Kong',
       'British Virgin Islands;Belarus', 'British Virgin Islands;CuraÃ§ao',
       'Australia;British Virgin Islands',
       'Vanuatu;British Virgin Islands', 'Germany;British Virgin Islands',
       'Not identified;Cayman Islands', 'Croatia;British Virgin Islands',
       'Belize;British Virgin Islands', 'Not identified;Luxembourg',
       'Not identified;United States;Canada', 'Cyprus;Samoa',
       'Not identified;Costa Rica', 'Not identified;Finland',
       'British Virgin Islands;Turks and Caicos Islands',
       'Turks and Caicos Islands;British Virgin Islands',
       'Not identified;Austria', 'British Virgin Islands;Switzerland',
       'United States;Saint Kitts and Nevis', 'Not identified;France',
       'Fiji;British Virgin Islands',
       'Not identified;United Arab Emirates', 'Guernsey;Not identified',
       'Belize;Not identified', 'British Virgin Islands;Barbados',
       'Bahamas;Not identified', 'British Virgin Islands;Puerto Rico',
       'Not identified;Malta', 'British Virgin Islands;Croatia',
       'British Virgin Islands;Belize', 'Cyprus;Saint Kitts and Nevis',
       'Costa Rica;Not identified', 'British Virgin Islands;New Zealand',
       'Puerto Rico;British Virgin Islands',
       'Malta;British Virgin Islands', 'Not identified;Australia',
       'United Kingdom;United States', 'Not identified;Poland',
       'Turks and Caicos Islands;United States',
       'Luxembourg;Not identified', 'Romania;Not identified',
       'Serbia;British Virgin Islands', 'Not identified;Philippines',
       'Not identified;Turks and Caicos Islands', 'Not identified;Belize',
       'Not identified;South Korea', 'Not identified;Belarus',
       'Not identified;Italy', 'New Zealand;British Virgin Islands',
       'France;British Virgin Islands', 'Belgium;British Virgin Islands',
       'CuraÃ§ao;Not identified', 'Not identified;Spain',
       'United Arab Emirates;Not identified', 'Not identified;Thailand',
       'United States;Turks and Caicos Islands', 'Belgium;Not identified',
       'Latvia;Samoa', 'United Kingdom;Russia',
       'Czech Republic;Turks and Caicos Islands',
       'Not identified;Vanuatu', 'British Virgin Islands;Netherlands',
       'Not identified;CuraÃ§ao', 'Not identified;Mexico',
       'Isle of Man;Not identified', 'Kazakhstan;British Virgin Islands',
       'Seychelles;Belize', 'Panama;Mauritius',
       'Saint Kitts and Nevis;Russia', 'Saint Kitts and Nevis;Latvia',
       'United Kingdom;Belize', 'Canada;United Kingdom',
       'British Virgin Islands;Portugal', 'Japan;British Virgin Islands',
       'Not identified;Georgia',
       'Turks and Caicos Islands;Czech Republic',
       'British Virgin Islands;France', 'British Virgin Islands;Serbia',
       'Seychelles;United States', 'Mexico;Not identified',
       'United Kingdom;Antigua and Barbuda',
       'Bermuda;British Virgin Islands',
       'British Virgin Islands;Kazakhstan',
       'British Virgin Islands;South Africa', 'Croatia;Not identified',
       'Saint Kitts and Nevis;British Virgin Islands',
       'United Kingdom;Turks and Caicos Islands',
       'U.S. Virgin Islands;Not identified',
       'Not identified;South Africa', 'Hong Kong;Mauritius',
       'Kuwait;British Virgin Islands', 'United States;Mauritius',
       'United Arab Emirates;Seychelles', 'Belarus;Not identified',
       'Not identified;Venezuela', 'Latvia;Saint Kitts and Nevis',
       'Australia;Belize', 'South Africa;Not identified',
       'Russia;Saint Kitts and Nevis', 'Portugal;British Virgin Islands',
       'Belize;United Kingdom', 'CuraÃ§ao;Netherlands;Not identified',
       'Israel;British Virgin Islands', 'Not identified;Japan',
       'Greece;Not identified', 'Hong Kong;Saint Kitts and Nevis',
       'United States;Panama', 'Syria;British Virgin Islands',
       'United Kingdom;Estonia', 'Andorra;Not identified',
       'Not identified;Grenada', 'Mauritius;Hong Kong',
       'British Virgin Islands;Bahamas', 'Canada;Saint Kitts and Nevis',
       'Saint Kitts and Nevis;United Kingdom', 'France;Not identified',
       'British Virgin Islands;Israel', 'Kazakhstan;Not identified',
       'Seychelles;United Arab Emirates', 'Spain;British Virgin Islands',
       'Saint Kitts and Nevis;Canada', 'Panama;Russia',
       'United Kingdom;Canada;Not identified',
       'British Virgin Islands;Liechtenstein',
       'Turks and Caicos Islands;United Arab Emirates',
       'Hong Kong;Philippines;British Virgin Islands', 'Singapore;Taiwan',
       'Bahamas;Panama', 'Cayman Islands;Panama',
       'Cook Islands;Not identified', 'Switzerland;Cook Islands',
       'Saint Kitts and Nevis;United Arab Emirates',
       'Norway;Not identified', 'Not identified;Canada;United Kingdom',
       'Spain;Not identified', 'Saint Kitts and Nevis;Sweden',
       'British Virgin Islands;Kuwait', 'Kuwait;Not identified', 'Uganda',
       'Central African Republic'], dtype=object)

# Identifying the weird values in the columns itself.

From this, we identified that 

Under Jurid, we have weird values such as 
-  'Recorded in leaked files as "fund"'
-   'Undetermined'

Under countries, we have 

- A lot of values with the ';' which is a combination of countries
- 'Not identified'
- NaN


We will remove all these

In [13]:
df_edges = df_edges.dropna()
df_edges = df_edges[ df_edges['jurisdiction_description'] != 'Undetermined']
df_edges = df_edges[ df_edges['jurisdiction_description'] !=  'Recorded in leaked files as "fund"']
df_edges = df_edges[~df_edges['countries'].str.contains(';')]
df_edges = df_edges[ df_edges['countries'] != 'Not identified']

# Grouping them into countries together

In [15]:
df_edges

       jurisdiction_description             countries
0                         Samoa             Hong Kong
1                         Samoa             Hong Kong
2                         Samoa             Hong Kong
3                         Samoa             Hong Kong
4                         Samoa             Hong Kong
5                         Samoa             Hong Kong
6                         Samoa             Hong Kong
7                         Samoa             Hong Kong
8                         Samoa             Hong Kong
9                         Samoa             Hong Kong
10                        Samoa             Hong Kong
11                        Samoa             Hong Kong
12                        Samoa                Taiwan
13                        Samoa                 China
14                        Samoa             Hong Kong
15                        Samoa             Hong Kong
16                        Samoa             Hong Kong
17                        Samoa                 China
18                        Samoa           Switzerland
19                        Samoa             Hong Kong
20                        Samoa             Singapore
21                        Samoa                Taiwan
22                        Samoa                Taiwan
23                        Samoa                Taiwan
24                        Samoa           Switzerland
25                        Samoa           Switzerland
26                        Samoa                Brazil
27                        Samoa           Switzerland
28                        Samoa             Hong Kong
29                        Samoa                Taiwan
...                         ...                   ...
319428                   Panama                Panama
319429                  Bahamas                Panama
319430                  Bahamas  United Arab Emirates
319431                  Bahamas             Venezuela
319432                  Bahamas                Cyprus
319433                  Bahamas               Bahamas
319434                  Bahamas               Bahamas
319435                  Bahamas            Luxembourg
319436                  Bahamas           Isle of Man
319437                  Bahamas               Bahamas
319438                  Bahamas                Panama
319439                  Bahamas                Jersey
319440                   Panama                Jersey
319441                  Bahamas                Jersey
319442                  Bahamas           Switzerland
319443                   Belize              Colombia
319444                   Panama        United Kingdom
319446                  Bahamas           Isle of Man
319447                   Belize                Panama
319448                   Panama          South Africa
319449                   Panama        United Kingdom
319450                   Belize              Colombia
319451                   Panama              Guernsey
319452                   Panama              Guernsey
319453                   Panama               Germany
319454                   Panama            Luxembourg
319455                   Panama                Jordan
319456                   Panama                Monaco
319457                   Panama             Hong Kong
319458                  Bahamas           Switzerland

[259737 rows x 2 columns]

In [17]:
df_edges_overall = df_edges.groupby(['jurisdiction_description', 'countries']).size().reset_index(name = 'Freq')

In [21]:
df_edges_overall.columns = ['target', 'source', 'weight']
#jurisdiction_description = target
#countries = source

In [19]:
df_edges_overall

                       target                  source  weight
0                     Bahamas                 Albania       2
1                     Bahamas                 Andorra      26
2                     Bahamas               Argentina      23
3                     Bahamas               Australia       2
4                     Bahamas                 Austria       4
5                     Bahamas              Azerbaijan       4
6                     Bahamas                 Bahamas     428
7                     Bahamas                Barbados       2
8                     Bahamas                 Belgium       8
9                     Bahamas                  Belize     250
10                    Bahamas                 Bermuda      19
11                    Bahamas                  Brazil      33
12                    Bahamas  British Virgin Islands     145
13                    Bahamas                Bulgaria       2
14                    Bahamas                  Canada      35
15                    Bahamas          Cayman Islands       7
16                    Bahamas                   Chile      14
17                    Bahamas                   China       5
18                    Bahamas                Colombia      22
19                    Bahamas              Costa Rica      32
20                    Bahamas                  Cyprus     649
21                    Bahamas          Czech Republic       2
22                    Bahamas                 Denmark       4
23                    Bahamas      Dominican Republic       8
24                    Bahamas                 Ecuador      49
25                    Bahamas                   Egypt       5
26                    Bahamas             El Salvador       6
27                    Bahamas                 Estonia     114
28                    Bahamas                 Finland      32
29                    Bahamas                  France      23
..                        ...                     ...     ...
837            United Kingdom             Switzerland       2
838            United Kingdom          United Kingdom      54
839            United Kingdom           United States       5
840            United Kingdom                 Uruguay       3
841  United States Of America           United States       2
842                   Uruguay                 Andorra      15
843                   Uruguay                 Bahamas       2
844                   Uruguay                  Brazil       1
845                   Uruguay                Colombia       1
846                   Uruguay                 Ecuador       2
847                   Uruguay                Guernsey       1
848                   Uruguay             Isle of Man       1
849                   Uruguay              Luxembourg       1
850                   Uruguay                  Panama       7
851                   Uruguay                  Russia       2
852                   Uruguay                   Spain       3
853                   Uruguay             Switzerland       2
854                   Uruguay                 Uruguay      12
855                   Uruguay               Venezuela       2
856                   Vanuatu                 Vanuatu       4
857                   Wyoming                 Bahamas      15
858                   Wyoming                  Belize       1
859                   Wyoming                  Brazil       4
860                   Wyoming                   Chile       1
861                   Wyoming                  Jersey       1
862                   Wyoming              Luxembourg       1
863                   Wyoming                  Panama       5
864                   Wyoming                  Poland       1
865                   Wyoming          United Kingdom       1
866                   Wyoming                 Uruguay       7

[867 rows x 3 columns]

# It is interesting to note that there are sizeable amount of self loops

Eg. Bahamas to Bahamas 400 records

In [23]:
df_edges_overall.to_csv('edgesbetweencountries.csv', index = False)